# Generated by Django 4.2.9 on 2024-06-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_permission",
            field=models.BooleanField(default=True, verbose_name="Уведомления"),
        ),
    ]
