# Generated by Django 4.2.9 on 2024-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identification_code",
            field=models.IntegerField(default=0, verbose_name="Код для подтверждения пользователя"),
        ),
        migrations.AddField(
            model_name="user",
            name="identification_code_entry_attempts",
            field=models.IntegerField(default=0, verbose_name="Попытки ввода кода"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Имя пользователя"),
        ),
    ]
