# Generated by Django 4.2.9 on 2024-06-11 11:35

from django.db import migrations, models
import study_on.services.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(verbose_name="Текст")),
                ("video", models.URLField(blank=True, verbose_name="Видео")),
                ("image", models.FileField(blank=True, upload_to="images", verbose_name="Изображение")),
                ("order", study_on.services.fields.OrderField(blank=True, verbose_name="Порядок")),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
            ],
            options={
                "verbose_name": "Содержание",
                "verbose_name_plural": "Содержание",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Ссылка")),
                ("image", models.ImageField(blank=True, null=True, upload_to="posts", verbose_name="Изображение")),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
