# Generated by Django 4.2.9 on 2024-06-14 19:46

from django.db import migrations, models
import study_on.services.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(verbose_name="Ответ")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Правильность")),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="AvailableLessons",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "max_available_lesson",
                    models.PositiveIntegerField(default=0, help_text="Номер урока", verbose_name="Доступный урок"),
                ),
            ],
            options={
                "verbose_name": "Доступные уроки курса",
                "verbose_name_plural": "Доступные уроки курса",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Закладка",
                "verbose_name_plural": "Закладки",
            },
        ),
        migrations.CreateModel(
            name="Completion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Завершенный курс",
                "verbose_name_plural": "Завершенные курсы",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(verbose_name="Текст")),
                ("video", models.URLField(blank=True, verbose_name="Видео")),
                ("image", models.FileField(blank=True, upload_to="images", verbose_name="Изображение")),
                ("order", study_on.services.fields.OrderField(blank=True, verbose_name="Порядок")),
                ("is_published", models.BooleanField(default=False, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Содержание",
                "verbose_name_plural": "Содержание",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(max_length=500, verbose_name="Описание")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Ссылка")),
                ("is_published", models.BooleanField(default=False, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Heading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Направление")),
                ("description", models.TextField(verbose_name="Описание")),
                ("is_published", models.BooleanField(default=False, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(max_length=500, verbose_name="Описание")),
                ("order", study_on.services.fields.OrderField(blank=True, verbose_name="Порядок")),
                ("is_published", models.BooleanField(default=False, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("text", models.TextField(max_length=400, verbose_name="Текст вопроса")),
                ("order", study_on.services.fields.OrderField(blank=True, verbose_name="Порядок")),
                ("is_published", models.BooleanField(default=False, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(blank=True, verbose_name="Текст отзыва")),
                (
                    "grade",
                    models.PositiveIntegerField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=0,
                        help_text="Оценка от 0 до 5",
                        verbose_name="Оценка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Ссылка")),
                ("is_published", models.BooleanField(default=False, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(max_length=500, verbose_name="Описание")),
                ("is_published", models.BooleanField(default=False, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="SurveyStudent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_passed", models.BooleanField(default=False, verbose_name="Пройден")),
            ],
            options={
                "verbose_name": "Тест студента",
                "verbose_name_plural": "Тесты студентов",
            },
        ),
    ]
